### ISSUE TITLE
A request to the base URI should redirect to /ssh/default

### ISSUE THREAD

**Issue by ericfranz** [OSC/ood-shell#22]
Currently if I go to https://ondemand.osc.edu/pun/sys/shell I see this:

>Cannot GET /pun/sys/shell

Instead, it should redirect to /pun/sys/shell/ssh/default.

In the future, another option would be to show a form with launch options (choose host and theme).

**Comment by nickjer** [comment]
This would break if a directory was specified...

```
https://ondemand.osc.edu/pun/sys/shell/path/to/directory
```

Would removing `/ssh/default` provide any benefit besides less text to type?

**Comment by ericfranz** [comment]
Keep `/ssh/default`. The example you give should return 404. But the root request to every app should return something sensible - not 404 or crash. Similar to specifying the `root` in `config/routes.rb`, a GET request to the root of the app should do something sensible. The simplest is to redirect to `/ssh/default/`

**Comment by ericfranz** [comment]
Adding this redirect for requests to the application root would actually provide 2 benefits:

1. when installing the shell app following default installation, its easy to go to the root and confirm it works, without having to think and remember that I need to add `/ssh/default` to the end (arguably, we should do something similar to file-editor)
2. it could offer some option in the future when auto-adding the nav bar link to the shell app, for the shell app that doesn't have cluster specific links to just link to the shell's root instead of special casing `/ssh/default` (not sure though)

**Comment by nickjer** [comment]
Another option is to set it to the root path for the app, and pass in host/path as query params...

```
https://domain.com/shell?host=oakley&path=...
```

**Comment by nickjer** [comment]
This would require an updated in `OodAppkit` for the URL generator, and all the apps to use the latest `ood_appkit` gem.

**Comment by ericfranz** [comment]
Lets just do this:

1. `https://ondemand.osc.edu/pun/sys/shell/path/to/directory` should return 404; no one uses this; if you are trying to connect to an app from the dashboard or another app link, you are using `https://ondemand.osc.edu/pun/sys/shell/ssh/HOST/PATH` or `https://ondemand.osc.edu/pun/sys/shell/ssh/HOST`
2. A GET request directly to `https://ondemand.osc.edu/pun/sys/shell` should redirect to `https://ondemand.osc.edu/pun/sys/shell/ssh/default`

**Comment by nickjer** [comment]
1. It already returns a 404.
2. This can be added.

**Comment by nickjer** [comment]
Note that not all `https://ondemand.osc.edu/pun/sys/shell/path/to/directory` return 404. Some of them are needed for assets...

```
https://ondemand.osc.edu/pun/sys/shell/wetty/hterm_all.js
https://ondemand.osc.edu/pun/sys/shell/socket.io/socket.io.js
```
