### ISSUE TITLE
When DEFAULT_SSHHOST is not set, should we ssh to localhost or just start bash?

### ISSUE THREAD

**Issue by ericfranz** [OSC/ood-shell#27]
Reproduced in OSC OnDemand.

If I follow the directions for installing the shell app, but I:

1. build the app in my dev sandbox via git clone + npm install
2. access the app without specifying a `DEFAULT_SSHHOST` in `.env`, navigating to `/pun/dev/shell/ssh/default`

The result is I attempt to ssh to localhost. This is because https://github.com/OSC/ood-shell/blob/69be0977b2be2bf70e6fb05b1cc385a288593eb7/app.js#L76 resolves the host to 'localhost' when the environment variable is not set.

Of course, in the case of this web host, it fails. Perhaps this is desired functionality.

Is this the desired outcome? Since we are using `forkpty(3)` we could get away with in the `localhost` case replacing:

```js
var term_args = [sshhost, '-p', sshport];
// set the directory to cd to
if (cwd !== null) {
  term_args.push('-t', 'cd ' + cwd + ' ; exec bash -l');
}

// launch an ssh session
var term = pty.spawn('ssh', term_args, {
  name: 'xterm-256color',
  cols: 80,
  rows: 30
});
```

with something like

```js
var term = pty.spawn('sh', ['-l'], {
  name: 'xterm-256color',
  cols: 80,
  rows: 30,
  // set the directory to cd to
  cwd: cwd || process.env.HOME,
  // omit variables that should not be passed to this child process
  env: _.omit(process.env, ['RAILS_ENV', 'RACK_ENV', 'RACK_BASE_URI',
    'PASSENGER_DEBUG_DIR', 'PASSENGER_BASE_URI', 'PASSENGER_APP_ENV',
    'RAILS_RELATIVE_URL_ROOT', 'NODE_ENV', 'IN_PASSENGER', 'DOCUMENT_ROOT',
    'REQUEST_METHOD', 'REQUEST_URI'])
});
```

**Comment by nickjer** [comment]
The user's shell may not be `sh`. Also you don't specify `cd`'ing into directories.

Also there are other environment variables that are not being set in this situation like `$LANG` and `$SHELL` that introduce problems further down the line.

It is best to use `ssh` so the terminal process is started as a clean login shell.
