### ISSUE TITLE
Key's do not repeat

### ISSUE THREAD

**Issue by ericfranz** [OSC/ood-shell#44]
Press and hold the lowercase L key i.e. l. Instead of repeating l's: llllllll, a helper is displayed:

<img width="281" alt="screen 2017-12-04 at 6 42 48 pm" src="https://user-images.githubusercontent.com/512333/33582398-11c4e928-d923-11e7-9d22-f8074fd96bfe.png">

This is bad because it makes using vim or other text editors very difficult.

**Comment by nickjer** [comment]
This is not reproducible on Windows/Chrome. This was so far only observed on Macs. Do you happen to know what the Mac is doing when it displays that, or what that feature might be called to help narrow it down?

**Comment by nickjer** [comment]
This may be a feature built into OSX and not an issue with the Shell app:

http://osxdaily.com/2011/08/04/enable-key-repeat-mac-os-x-lion/

Can you confirm if you see this behavior in other OSX tools?

**Comment by nickjer** [comment]
@basilgohar has confirmed he sees this behavior in iTerm as well, so I suggest we close this issue.

**Comment by nickjer** [comment]
This was discussed and decided this wasn't a bug. So closing for now.
