### ISSUE TITLE
Should the default behavior of the shell accessing localhost be ssh or should localhost be prevented by default?

### ISSUE THREAD

**Issue by ericfranz** [OSC/ood-shell#51]
Preventing localhost from being accessible, or at least defaulting to forking ssh might be preferable to forking bash by default.

@Robbe7730 do you have any thoughts on this? What was your motivation for adding the SSH_LOCALHOST configuration option?

**Comment by Robbe7730** [comment]
We tought it wasn't logical that `.../ssh/localhost` would start up a bash shell and not actually use ssh. Also, we are running nginx in a namespace, restricting access to certain folders, so if a bash shell is started, this would also be inside the namespace and thus have other permissions than the user would via ssh.

We are going to leave it disabled for our setup, but maybe having bash available as `.../bash` for example is a better alternative?

**Comment by ericfranz** [comment]
We talked internally and decided we are going to remove the local host bash feature. So now, instead, everything will be using ssh and the SSH_LOCALHOST config will be unnecessary. Opened a separate issue to track that work so we can close this now.
