### ISSUE TITLE
Ctrl-V paste in Microsoft Edge pastes the text twice

### ISSUE THREAD

**Issue by ericfranz** [OSC/ood-shell#59]
Copy works well in MS Edge (except for #57). Paste, however, pastes the text two times.

Notice I've copied the text "webhooks.conf" by selecting it. Then I can paste it in notepad, showing there is only 1 copy of the string in the clipboard. But if I paste in the shell app it inserts the text twice.

![screen 2018-12-27 at 1 52 54 pm](https://user-images.githubusercontent.com/512333/50491231-431f6a00-09df-11e9-93ca-61c12b99cce3.png)

![screen 2018-12-27 at 1 53 10 pm](https://user-images.githubusercontent.com/512333/50491236-46b2f100-09df-11e9-8ae2-6d3ff9de63c2.png)

It appears the paste event handler is being executed twice in Edge? OR something else. Regardless, we might consider not fixing this due to https://github.com/OSC/ood-shell/issues/57#issuecomment-445033416 and https://www.zdnet.com/article/microsofts-edge-to-morph-into-a-chromium-based-cross-platform-browser/

**Comment by MorganRodgers** [comment]
Today, with Edge 42.17134.1.0 we got different behaviors. When the user types `control-v` the app might:

- Reload itself
- Show an error
- Paste text

**Comment by MorganRodgers** [comment]
Fixed in #65.
