### ISSUE TITLE
Paste in MS Edge causes page to reload

### ISSUE THREAD

**Issue by johrstrom** [OSC/ood-shell#62]
Pasting data (through ctrl+v or ctrl+shift+v or shift+insert) in MS edge into the shell causes the page to reload.  There are no logs in the console as to why this is happening and I cannot seem to find an appropriate way to "capture" the core dump equivalent.  

Interestingly enough, while using the debugger and setting a break point - this doesn't happen. I.e., breakpoints and pausing execution seems to resolve the issue.

**Comment by MorganRodgers** [comment]
Fixed in #65.
